apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafkasql-journal
  labels:
    strimzi.io/cluster: cluster
  namespace: apicurio-demo
spec:
  partitions: 2
  replicas: 1
  config:
    cleanup.policy: compact