apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster
  namespace: apicurio-demo
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '3.4'
      inter.broker.protocol.version: '3.4'
    authorization:
      type: simple
    storage:
      type: persistent-claim
      size: 5Gi
    listeners:
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        type: internal
        tls: true
    version: 3.4.0
    replicas: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: persistent-claim
      size: 5Gi
    replicas: 3
